name: pipeline-to-ELB

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
 deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: read 
        packages: write

    steps:
    - name: Checkout code (clone repo)
      uses: actions/checkout@v2

    - name: install java and setup maven
      uses: actions/setup-java@v3
      with:
        distribution: "adopt"   
        java-version: '11'
    - name: sonarqube analysis 
      run: mvn sonar:sonar -Dsonar.projectKey=${{secrets.SONAR_PROJECT_KEY}} -Dsonar.host.url=${{secrets.SONAR_HOST_URL}} -Dsonar.login=${{secrets.SONAR_LOGIN_TOKEN}}

    - name: maven build
      run: mvn clean package 

    - name: Upload to artifact repo 
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Authenticate to AWS 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
        aws-region: ${{secrets.AWS_REGION}} 


    - name: Copy artifact to s3 
      run: aws s3 cp target/*war s3://artifact-repo-charlo


    - name: create an application version 
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name xashy-webapp \
        --source-bundle S3Bucket="artifact-repo-charlo",S3Key="xashy-webapp.war" \
        --version-label "ver-${{ github.sha }}" \
        --description "commit-sha-${{ github.sha }}"

    - name: deploy the app to elastic beanstalk enviroment 
      run: aws elasticbeanstalk update-environment --environment-name Web-app-dev-env --version-label "ver-${{ github.sha }}" --version-label "ver-${{ github.sha }}" 